###############################################################################
# Precompiled Headers Management
#
# This module provides functions for managing Precompiled Headers (PCH).
# PCH significantly speeds up compilation by pre-processing commonly used
# headers once and reusing them across all translation units (i.e. STL headers).
#
# Functions:
#   ensure_global_pch_target_exists() - Create global PCH target (internal)
#   target_use_global_pch(<target>)   - Use global PCH on a target
#   target_enable_pch(<target> ...)   - Use custom headers list on a target
#   target_configure_pch(<target> ..) - Auto-select global or custom PCH
#
# Usage:
#   # Either use the generated global PCH
#   target_use_global_pch(mylib)
#
#   # Or use a custom PCH file from the module directory
#   target_configure_pch(mylib PCH pch/pch.hpp)
#
#   # Or per-target PCH with inline headers list
#   target_enable_pch(mylib
#       HEADERS <vector> <string> <memory>
#   )
###############################################################################


###############################################################################
# ensure_global_pch_target_exists()
#
# Create a global PCH target if it doesn't exist yet. The PCH includes common
# STL headers that are used throughout the project. Using a global PCH avoids
# recompiling the same headers for each module. This target is compiled once
# and reused by all modules.
#
# Generated files:
#   - ${CMAKE_BINARY_DIR}/generated/global_pch.hpp     : PCH header
#   - ${CMAKE_BINARY_DIR}/generated/global_pch.cpp     : Empty source (required by CMake)
#   - ${CMAKE_BINARY_DIR}/generated/global_pch.hpp.gch : Compiled PCH (GCC)
#   - ${CMAKE_BINARY_DIR}/generated/global_pch.hpp.pch : Compiled PCH (Clang)
###############################################################################

function(ensure_global_pch_target_exists)

    # Skip if target already exists
    if(TARGET global_pch)
        return()
    endif()

    message(STATUS "  Creating global PCH target: global_pch")

    set(_pch_header_path "${CMAKE_BINARY_DIR}/generated/global_pch.hpp")
    set(_pch_source_path "${CMAKE_BINARY_DIR}/generated/global_pch.cpp")

    # Ensure directory exists
    file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/generated")

    # Create the PCH header with common includes
    # file(CONFIGURE) only writes if content changed, avoiding
    # unnecessary PCH recompilation on every cmake reconfigure.
    # NOTE: file(CONFIGURE) uses @VAR@ syntax, not ${VAR}
    # Use NEWLINE_STYLE UNIX to ensure consistent line endings
    file(CONFIGURE
        OUTPUT "${_pch_header_path}"
        CONTENT [[
// ==========================================================================
// global_pch.hpp - Global Precompiled Header
// ==========================================================================
// This file is auto-generated by CMake. Do not edit manually.
// Add headers here that are:
//   1. Frequently included across the project
//   2. Rarely modified
//   3. Large (lots of code to parse)
//
// Custom PCH files can include this file:
//   #include "global_pch.hpp"
// ==========================================================================

#ifndef GLOBAL_PCH_HPP
#define GLOBAL_PCH_HPP

// C++ Standard Library - Containers
#include <array>
#include <deque>
#include <list>
#include <map>
#include <set>
#include <unordered_map>
#include <unordered_set>
#include <vector>

// C++ Standard Library - Strings
#include <string>
#include <string_view>

// C++ Standard Library - Memory
#include <memory>

// C++ Standard Library - Utilities
#include <algorithm>
#include <functional>
#include <optional>
#include <tuple>
#include <utility>
#include <variant>

// C++ Standard Library - I/O
#include <iostream>
#include <sstream>

// C++ Standard Library - Misc
#include <chrono>
#include <cstddef>
#include <cstdint>
#include <stdexcept>
#include <type_traits>

#endif // GLOBAL_PCH_HPP
]]
        NEWLINE_STYLE UNIX
    )

    # Empty source file required by add_library(STATIC).
    # CMake ignores .hpp files as non-compilable sources, so without this
    # .cpp file we'd get "No SOURCES given to target". The actual PCH
    # compilation is handled by target_precompile_headers() which invokes
    # the compiler with -x c++-header to produce the .gch/.pch binary.
    # This file must NOT #include global_pch.hpp — CMake injects it
    # automatically into all translation units that use this PCH.
    file(CONFIGURE
        OUTPUT "${_pch_source_path}"
        CONTENT [[
// Auto-generated empty source file for PCH target.
// Required by add_library(STATIC) but not used for PCH compilation.
// Do NOT add #include "global_pch.hpp" here — CMake handles PCH injection.
]]
        NEWLINE_STYLE UNIX
    )

    # Create PCH Target
    # This static library only exists to compile the PCH.
    # Other targets will REUSE_FROM this target.
    add_library(global_pch STATIC
        "${_pch_header_path}"
        "${_pch_source_path}"
    )

    # Mark as system headers to suppress warnings from STL
    target_include_directories(global_pch SYSTEM PUBLIC
        "${CMAKE_BINARY_DIR}/generated"
    )

    # Enable precompiled header
    target_precompile_headers(global_pch PUBLIC
        "${_pch_header_path}"
    )

    # Set folder for IDE organization
    set_target_properties(global_pch PROPERTIES
        FOLDER "Infrastructure"
    )

endfunction()


###############################################################################
# target_use_global_pch(<target>)
#
# Configure a target to use the global precompiled header.
# All targets share the same compiled PCH, reducing build times.
#
# Arguments:
#   target_name - The CMake target to configure
#
# Example:
#   add_library(mylib src/mylib.cpp)
#   target_use_global_pch(mylib)
###############################################################################

function(target_use_global_pch target_name)

    # Ensure global PCH target exists
    ensure_global_pch_target_exists()

    # Reuse PCH from global target
    # REUSE_FROM shares the compiled PCH, avoiding recompilation
    target_precompile_headers(${target_name} REUSE_FROM global_pch)

    # Link to get include directories
    target_link_libraries(${target_name} PRIVATE global_pch)

endfunction()


###############################################################################
# target_enable_pch(<target>
#                   HEADERS <header1> <header2> ...
#                   [PRIVATE|PUBLIC|INTERFACE])
#
# Configure a target with a custom precompiled header.
# Use this when a target needs headers not in the global PCH.
#
# Arguments:
#   target_name - The CMake target to configure
#   HEADERS     - List of headers to precompile
#   PRIVATE     - PCH is only used by this target (default)
#   PUBLIC      - PCH propagates to targets that link to this one
#   INTERFACE   - PCH only propagates, not used by this target
#
# Example:
#   add_library(mylib src/mylib.cpp)
#   target_enable_pch(mylib
#       HEADERS
#           <vector>
#           <string>
#           <memory>
#           "mylib/common.h"
#   )
###############################################################################

function(target_enable_pch target_name)

    set(_options PRIVATE PUBLIC INTERFACE)
    set(_single_values)
    set(_multi_values HEADERS)
    cmake_parse_arguments(ARG "${_options}" "${_single_values}" "${_multi_values}" ${ARGN})

    if(NOT ARG_HEADERS)
        message(FATAL_ERROR "target_enable_pch: HEADERS argument is required")
    endif()

    # Determine visibility
    if(ARG_PUBLIC)
        set(_visibility PUBLIC)
    elseif(ARG_INTERFACE)
        set(_visibility INTERFACE)
    else()
        set(_visibility PRIVATE)
    endif()

    target_precompile_headers(${target_name} ${_visibility}
        ${ARG_HEADERS}
    )

endfunction()


###############################################################################
# target_configure_pch(<target> [PCH <path>])
#
# Configure PCH for a target, choosing between global or custom PCH.
#
# Arguments:
#   target_name - The CMake target to configure
#   PCH         - Optional path to custom PCH header, relative to
#                 CMAKE_CURRENT_SOURCE_DIR (e.g., pch/pch.hpp)
#
# Behavior:
#   - Without PCH argument: uses global PCH (REUSE_FROM global_pch)
#   - With PCH argument: compiles a dedicated PCH for this target
#     The target can optionally include the global PCH via:
#       #include "global_pch.hpp"  // from ${CMAKE_BINARY_DIR}/generated/
#
# Example:
#   # Use global PCH (default)
#   target_configure_pch(mylib)
#
#   # Use custom PCH from module's pch/ directory
#   target_configure_pch(mylib PCH pch/pch.hpp)
#
# The custom PCH file typically lives in:
#   <module>/
#   ├── pch/
#   │   └── pch.hpp     # Custom precompiled header
#   └── src/
#       └── ...
#
# Custom PCH can include the global PCH:
#   // mymodule/pch/pch.hpp
#   #pragma once
#   #include "global_pch.hpp"  // Global PCH (STL headers)
#   #include <boost/asio.hpp>  // Module-specific headers
###############################################################################

function(target_configure_pch target_name)

    set(_options)
    set(_single_values PCH)
    set(_multi_values)
    cmake_parse_arguments(ARG "${_options}" "${_single_values}" "${_multi_values}" ${ARGN})

    if(ARG_UNPARSED_ARGUMENTS)
        message(FATAL_ERROR "target_configure_pch: Invalid argument(s): ${ARG_UNPARSED_ARGUMENTS}")
    endif()

    if(ARG_PCH)
        # Custom PCH: compile a dedicated PCH for this target
        set(_pch_path "${CMAKE_CURRENT_SOURCE_DIR}/${ARG_PCH}")
        if(NOT EXISTS "${_pch_path}")
            message(FATAL_ERROR "target_configure_pch: PCH file not found: ${_pch_path}")
        endif()

        # Ensure global PCH directory exists (for potential inclusion)
        ensure_global_pch_target_exists()

        # Add generated directory so custom PCH can #include "global_pch.hpp" (global PCH)
        target_include_directories(${target_name} PRIVATE
            "${CMAKE_BINARY_DIR}/generated"
        )

        target_precompile_headers(${target_name} PRIVATE "${_pch_path}")
    else()
        # Global PCH: reuse the shared precompiled header
        target_use_global_pch(${target_name})
    endif()

endfunction()
