###############################################################################
# Crash Stack Traces
#
# Provides human-readable stack traces on segfaults/crashes via backward-cpp.
# Fully transparent: executables get stack traces automatically in Debug builds.
# No user code required.
#
# Prerequisites (for full traces):
#   sudo apt install libdw-dev          # libdw backend (recommended)
#   sudo apt install binutils-dev       # addr2line backend (fallback)
###############################################################################

option(ENABLE_STACKTRACE "Enable backward-cpp crash stack traces" ON)

if(ENABLE_STACKTRACE)

    print_box("backward-cpp Stack Traces")

    # Conan recipe exposes cmake_file_name="Backward", target="Backward::Backward"
    find_conan_package(Backward REQUIRED)
    if(TARGET Backward::Backward)
        message(STATUS "backward-cpp: Target Backward::Backward available")
    endif()

    # Fallback alias if Conan uses raw package name
    if(NOT TARGET Backward::Backward AND TARGET backward-cpp::backward-cpp)
        add_library(Backward::Backward ALIAS backward-cpp::backward-cpp)
        message(STATUS "backward-cpp: Created alias Backward::Backward")
    endif()

    # Generate stacktrace init source for Debug builds (registers signal handlers)
    file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/generated")
    set(_stacktrace_init "${CMAKE_BINARY_DIR}/generated/stacktrace_init.cpp")
    file(WRITE "${_stacktrace_init}"
        "// Auto-generated by Stacktrace.cmake - backward-cpp signal handlers (Debug only)\n"
        "// Do not edit.\n"
        "#include <backward.hpp>\n"
        "static backward::SignalHandling s_stacktrace_init;\n"
    )
    set(STACKTRACE_INIT_SOURCE "${_stacktrace_init}" CACHE INTERNAL "")
    message(STATUS "backward-cpp: Auto-init enabled (Debug build)")

    # Register for configuration summary 
    add_enabled_feature("Stacktrace")

endif()
